---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/kustomization.yaml
  prune: true
  sourceRef:
    branch: main
    kind: GitRepository
    name: fleet-infra
  targetNamespace: velero

